### ISSUE TITLE
Critical bug when trying to hash a 0 Byte file. 

### ISSUE THREAD

**Issue by Max-p-otential** [AlEscher/FileHasher#1]
Programm becomes unusable after trying to hash a file with 0 bytes in size.

Steps to reproduce:
1. create an empty txt file
2. add that file to the hash list
3. click generate hash
4. programm will freeze and not be able to generate any further hashes

**Comment by AlEscher** [comment]
Thanks for reporting this issue.
It should be fixed now, the newest release has been updated: https://github.com/AlEscher/FileHasher/releases/tag/v1.1
